### ISSUE TITLE
AutoReplace: the double quote “ is not accepted

### ISSUE THREAD

**Issue by hieuvijjo** [marginnoteapp/ohmymn#65]
The double quote `”` is not accepted in the replacement syntax.
For example, `(/xxx/, "111")` would work but `(/xxx/, ”111”)` wouldn’t. The difference is only the double quotes, `"` vs `”`. 
As `”` is the default double quote in iPad virtual keyboard, it creates a lot of confusion. It took me quite a while to realize what goes wrong with `”`.

**Comment by ourongxing** [comment]
That's the problem with the iPad

**Comment by hieuvijjo** [comment]
Could you please support `”` in the replacement syntax?
