### ISSUE TITLE
更新了mn4.11以后 换回4.00 一打开软件就闪退 除非禁止插件

### ISSUE THREAD

**Issue by xzbdmw** [marginnoteapp/ohmymn#68]

**Comment by ourongxing** [comment]
最好不要降级，而且这两个版本区别比较大，配置乱了。只能重置配置了

**Comment by xzbdmw** [comment]
> 最好不要降级，而且这两个版本区别比较大，配置乱了。只能重置配置了

主要是翻译的api失效了不得不升级 请问有本地数据库版本的4.0.0吗? 我只能找到4.1.1的 新版本有些bug不太好用

**Comment by ourongxing** [comment]
我只能说 4.0.0 的 bug 更多

**Comment by xzbdmw** [comment]
> 我只能说 4.0.0 的 bug 更多

4.1.1这个功能没了 想偶尔摘录带字符的标题不方便
<img width="284" alt="image" src="https://user-images.githubusercontent.com/97848247/226875202-2634a643-6e36-4de2-a208-8ddd5160ad8d.png">
那本地数据库只有4.1.1的吗
